version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - run:
          name: Run Test and Coverage
          command: npm test -- --coverage
  deploy:
    docker:
      - image: circleci/node:8
      steps:
        - run:
          name: Build & Deploy to GH Pages
          environment: 
            GITHUB_NAME: bobmchenry
            GITHUB_EMAIL: bobmchenryvideo@gmail.com
          command: |
            git config --global user.email "${GITHUB_NAME}"
            git config --global user.name "${GITHUB_EMAIL}"
            npm run deploy
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master