version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test and Coverage
          command: npm test
      - run:
          name: Build & Deploy to GH Pages
          environment: 
            GITHUB_NAME: bobmchenry
            GITHUB_EMAIL: bobmchenryvideo@gmail.com
          command: |
            git config --global user.email "${GITHUB_NAME}"
            git config --global user.name "${GITHUB_EMAIL}"
            npm run deploy
          